### ISSUE TITLE
Not working with SFTP

### ISSUE THREAD

**Issue by ManuelJm** [mkulke/ftplibpp#27]
Hi,
I've tried to use this library with a SFTP server, but the connect method always returns 0.

Does anyone knows how to use this lib with sftp?

The server i've tried is at:

199.71.215.197:2222

Works fine on FileZilla.

I've traced the code but i'm not able to figure out whats going on.
The problem seems the readline('2'... call which works ok nor normal ftp but not for sftp.

**Comment by mkulke** [comment]
SFTP is a completely different protocol, based on SSH. While _FTPS_ is a security extension to FTP.
