### ISSUE TITLE
not really an issue

### ISSUE THREAD

**Issue by mohamed--abdel-maksoud** [mkulke/ftplibpp#4]
First, thanks for the excellent library. I just wonder why in the sample program you use "new" instead of instantiating the class directly, i.e.
```
    ftplib ftp;
    ftp.Connect(config().host.c_str());
    int loggedin = ftp.Login(config().username.c_str(), password.c_str());
    ftp.Quit();
```

**Comment by mkulke** [comment]
Thanks, your code allocates the object on the stack, which means it is cleaned up, when „ftp“ goes out of scope. This is perfectly fine in many scenarios (you should prefer it to allocation with „new" wherever possible). However when you need the object outside of the scope in which it was created, you need to use „new“ to put the object on the heap, and free the space using „delete" when it’s not needed any more.
